### ISSUE TITLE
Systemize requires user interaction

### ISSUE THREAD

**Issue by jefflund** [jefflund/dot#10]
Scripts currently ask user to confirm an action with 'y' or 'yes' in a few places
- [ ] install/10-chrome.sh requires confirmation of install
- [ ] homedir/20-clone.py requires confirmation to add host

**Comment by jlund3** [comment]
For the homedir/20-clone.py problems, can use `ssh-keyscan -H <hostname> >> ~/.ssh/known_hosts` to add the missing keys before attempting to clone.
